Repository fire-square/autodonate, pull requests merged in 2022-04, with the labels that each got.

#43 Plugin API
  autodonate/__init__.py
  autodonate/app.py
  autodonate/module/__init__.py
  autodonate/plugin_manager.py
  autodonate/plugin_models.py
  autodonate/utils/config.py
  config.yml.example
  manage.py
  poetry.lock
  pyproject.toml
Labels: enhancement, python

#79 Добавил index приложение и static тэг
  CHANGELOG.md
  autodonate/lib/__init__.py
  autodonate/lib/templatetags/__init__.py
  autodonate/lib/templatetags/statictags.py
  autodonate/migrations/__init__.py
  autodonate/settings.py
  autodonate/urls.py
  index/__init__.py
  index/admin.py
  index/apps.py
  index/migrations/__init__.py
  index/models.py
  index/urls.py
  index/views.py
  templates/base.html
  templates/footer.html
  templates/header.html
Labels: python

#92 Parse sources instead of importing it in docs building
  .readthedocs.yml
  CHANGELOG.md
  docs/_autoapi_templates/index.rst
  docs/conf.py
  docs/index.rst
  docs/modules/modules.rst
  docs/remove_trash.py
  poetry.lock
  pyproject.toml
Labels: bug, documentation, python

#77 ZeroConfig концепция
  CHANGELOG.md
  autodonate/admin.py
  autodonate/models.py
  autodonate/settings.py
  poetry.lock
  pyproject.toml
Labels: enhancement, python

#101 Remove hard-coded year in docs
  docs/conf.py
Labels: bug, documentation
