Repository fire-square/autodonate, pull requests merged in 2022-03, with the labels that each got.

#27 Move ifmain block to function
  manage.py
Labels: enhancement, python

#26 Change poetry installation
  README.md
Labels: documentation, enhancement

#29 Add make docker command
  Makefile
Labels: enhancement

#30 Port logger from django branch :truck:
  autodonate/__init__.py
  autodonate/app.py
  autodonate/utils/__init__.py
  autodonate/utils/logger.py
  manage.py
Labels: enhancement, python, discussing

#35 Add bug report and PR templates
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/PULL_REQUEST_TEMPLATE.md
  .gitignore
Labels: documentation, enhancement

#37 Remove Python3.11 from CICD
  .github/workflows/test.yml
  CHANGELOG.md
Labels: bug, github_actions

#33 Add git pre-commit checks
  .pre-commit-config.yaml
  CONTRIBUTING.md
  poetry.lock
  pyproject.toml
Labels: enhancement, dependencies, github_actions, discussing

#38 Port Config class from `master`
  autodonate/__init__.py
  autodonate/utils/config.py
Labels: enhancement, python

#39 Add git pre-commit checks (duplicate #33)
  .pre-commit-config.yaml
  CONTRIBUTING.md
  poetry.lock
  pyproject.toml
Labels: duplicate, enhancement, dependencies, github_actions, discussing
