Repository fire-square/autodonate, pull requests merged in 2022-02, with the labels that each got.

#11 Добавил healthcheck адрес (#4)
  autodonate/urls.py
  autodonate/views.py
  poetry.lock
  pyproject.toml
  setup.cfg
  tests/models/test_payments.py
  tests/views/test_healthcheck.py
Labels: enhancement

#13 Add global cron thread
  autodonate/lib/utils/cron.py
  tests/cron/test_cron.py
Labels: enhancement

#18 Python 3.8 support
  .github/workflows/test.yml
  README.md
  autodonate/lib/utils/cron.py
  poetry.lock
  pyproject.toml
Labels: enhancement, dependencies, python

#16 Добавил API для платёжных шлюзов (#15)
  CHANGELOG.md
  autodonate/lib/payment/__init__.py
  autodonate/lib/payment/api.py
  autodonate/lib/payment/currencies.py
  autodonate/lib/payment/models.py
  autodonate/lib/payment/urls.py
  autodonate/migrations/0002_alter_payment_process.py
  autodonate/models.py
  autodonate/urls.py
  tests/cron/test_cron.py
  tests/payment/test_payment.py
Labels: enhancement

#20 Add isort formatter
  .github/workflows/test.yml
  CHANGELOG.md
  poetry.lock
  pyproject.toml
  setup.cfg
Labels: enhancement

#21 Move RCON to plugin autodonate-rcon-api
  autodonate/lib/utils/rcon.py
  autodonate/models.py
Labels: dependencies, python
